### ISSUE TITLE
Tackle that AugmintToken.sol contains loan/lock logic

### ISSUE THREAD

**Issue by szerintedmi** [Augmint/augmint-contracts#2]
Tackle [AugmintToken contract](https://github.com/Augmint/augmint-contracts/blob/staging/contracts/generic/AugmintToken.sol)'s convolution with loan/lock logic.

Ideally AugmintToken.sol should contain only pure ERC20 functions and issue/burn functions.

**Challenge**

-  we want the convenience for users to call 1 tx only (unlike using 2txs: `approve` + `transferFrom`). To achieve that  `repayLoan`, `placeOrderOnExchange` and `lockFunds` require to access user token balances.  
 All of those functions currently implemented in AugmintToken.sol
 
- certain params (e.g. `loanToDepositLockLimit`) and state (eg. `totalLoanAmount`) are global across multiple type (or versions) of loan / lock contracts. The state of totalLoanAmount and totalLockAmount needs to be maintained somewhere and ideally the limits should be enforced by a single contract (can't be counted in loan/lock contracts).
 All of these functions currently implemented in AugmintToken.sol

**Potential solutions**

1. use  [transferAndCall](https://github.com/ethereum/EIPs/issues/677) or [ERC-223](https://github.com/Dexaran/ERC223-token-standard) type generalisation (or something custom with that method)

1. split loans/locks logic into a separate contract where it inherits from (it would only help readability)

1. split loans/locks logic into separate lib (that would help contract size and readability)

1. separate loans/locks params into separate (potentially generic params) contract (partial solution)

Some combination of the above might be possible too.

**Comment by szerintedmi** [comment]
Based on discussions on [Augmint's Discord #contrac-dev channel](https://discord.gg/PwDmsnu)

 Current consensus is forming as:
 Aspiration is to `AugmintToken` only have issue and burn functions above the basic token functions.

To achieve that :
1. we would replace loan/lock/exchange convenience functions in `AugmintToken` with a generic [ERC667 style `transferAndCall`](https://github.com/ethereum/EIPs/issues/677).  
 See also: [Comparing ERC233 and ERC667](https://github.com/colucom/CLN-solidity/compare/erc223...erc677)

1.  `AugmintToken` loan/lock limit params and "KPI maintenance" (totalLoanAmount etc.) will be moved to a separate  `MonetarySupervisor` (name TBD) contract which will be called by the loan/lock/exchange contracts. These contracts are trusted in `AugmintToken` (i.e. whitelisted using `Restricted` to allow issue/burn)  so in order to whitelist them we must ensure they call `MonetarySupervisor` checks/housekeeping functions properly.

@phraktle @BYossarian ?

**Comment by phraktle** [comment]
Good summary.

Addition: ideally, only `MonetarySupervisor` should have privileges in `AugmintToken` (to mint new tokens) and all other contracts should go through the supervisor (which is where the loan etc contracts should be whitelisted).

Suggestion: rename `LoanManager` to `Lender`

**Comment by szerintedmi** [comment]
First pass for loan flow.
See a few questions around `issueTo` and `burnFrom`:
![loan flow](https://raw.githubusercontent.com/Augmint/augmint-contracts/916ba18b83e16becc0b5af90c6e0749305f06bd8/docs/loanFlow.png)

**Comment by szerintedmi** [comment]
second pass based on feedback form @phraktle  (thank you!)
![flow2ndpass](https://github.com/Augmint/augmint-contracts/raw/951f53faf3671b212ca3aef07e0801a71ed414a9/docs/loanFlow.png)

**Comment by phraktle** [comment]
For the record: I would refrain from adding duplicate methods with `narrative` and just stick to straightforward ERC20 (plus `transferAndCall`).

**Comment by szerintedmi** [comment]
Indeed, narratives is a discussion with wider audience :)

**Comment by phraktle** [comment]
To make it relevant for this use case: loan repayment should not need to add a narrative, since it's abundantly clear what happened even without a textual memo (money was repaid to a given loan).

**Comment by szerintedmi** [comment]
yep but `transferWithNarrative` is not introduced for that use case
anyways, happy to revisit  requirement for the narrative and definitely worth to think more about how could it be implemented better if we stick with it

**Comment by phraktle** [comment]
Well, you have to introduce even more duplicate methods beyond `transferWithNarrative`), just for the sake of the loan use cases. In fact you missed one already, I'll let you spot where :)

**Comment by szerintedmi** [comment]
yep, `tokenFallbackWithNarrative` is required. Wondering if we could use the data arg somehow for the narrative instead

**Comment by szerintedmi** [comment]
next iteration. removed transferAndCallWithNarrative Repayment won't have narrative, UI will have to deal displaying the tx  properly.
We keep `AugmintToken.transferWithNarrative` for manual transfers with memo. 
![loan flow pass3](https://github.com/Augmint/augmint-contracts/raw/b2005f148009398255631365c935932d759e56e6/docs/loanFlow.png)

**Comment by phraktle** [comment]
There's no need for `transferWithNarrative` calls in this sequence. I'd bet that even without the memo, the `InterestEarnedAccount` knows why the `Lender` gave it some cash :)

**Comment by szerintedmi** [comment]
left it there accidentally, fixed
![loan flow pass4](https://github.com/Augmint/augmint-contracts/raw/95e7fec06a16448901d7525c9cdfb19d6b676432/docs/loanFlow.png)

**Comment by szerintedmi** [comment]
I had a second thought about taking transfer fee from loan disbursement and repayment. We got to this compromise in order to get rid of an extra function we have now (ie. `transferNoFee`). 

But realised taking it would cause more issues/complications than I thought:

1. Transfer fee is taken from the sender. Where the tokens to cover Lender's transfer fee will come from? 
1. I feel not right to say to the borrower that you will get 1,000 A-EUR loan but you will receive 998 (we could pack/hide it on the UI but the contract would still show  1,000 for the loanAmount)
 or your repayment amount is 1,000 A_EUR but please get 1,002 A-EUR to repay it.
1. gas cost wise is an actual extra transfer for actually zero reason

**Comment by szerintedmi** [comment]
> 1. Lender should have earned it already (assuming interest rate > transfer fee).

Indeed. But it's just weird accounting.  I would park thinking over its implications until we settle on the next two points (i.e. this question might not be relevant)

> 2. That is a general problem with the way transfer fees are designed at the moment: users will have trouble paying their obligations exactly.

The possibility of 0 transfer fee tx solves the paying their obligation issue. Implementation wise there are other routes to implement it than as it is now (eg. instead of `transferNoFee` we could whitelist contract addresses which don't pay transfer fee).  
But what's the general problem? How could we tackle it?

If you have generic concerns with transfer fees i would appreciate to discuss it on a joint call - I would prefer more people to chip in :)

> 3. The price difference between transfer and transferNoFee should be quite small.

It's ca. 6k gas which is indeed not significant compared to the overall gas cost of loan/lock txs. Btw unit tests log gas consumption, you can see it on [Travis builds](https://travis-ci.org/Augmint/augmint-contracts/builds/338769880) too.

>(And if new tokens were minted directly into the recipients balance, there would be no need to transfer it)

Good point. It would mean a Transfer & AugmintTransfer from 0x0 to Borrower. But we got rid of narrative from loan disbursement transfer because we said that it will be obvious for borrower what's the transaction b/c the transfer came from Lender's address. It's not a deal breaker , just a note that UI will need to treat 0x0 transfers specially (ie. fetch additional tx details separately)

**Comment by szerintedmi** [comment]
Loan flow pass no. 4. Changed to issue tokens directly to borrower on new loan + added fee questions as notes:
![loan flow pass 4](https://github.com/Augmint/augmint-contracts/raw/c170993bca73cd9d5cdbd92d30abaac27697c037/docs/loanFlow.png)

**Comment by szerintedmi** [comment]
![Exchange flow first pass](https://github.com/Augmint/augmint-contracts/raw/770918506b294718941ca572d80820390d4a583e/docs/exchangeFlow.png)

**Comment by szerintedmi** [comment]
Loan flow next pass. Consensus for now ? :) 
![LoanFlow next pass](https://github.com/Augmint/augmint-contracts/raw/3bd7b5e96bae60496d8f3a2cb1ff7de5d8609a4d/docs/loanFlow.png)

**Comment by szerintedmi** [comment]
Exchange flow next pass, removed idx magic & alternative functions with approve (2 TXs) 
![Exchange flow next pass](https://github.com/Augmint/augmint-contracts/raw/9f72b8dea73c9640442bea3ca964a5857cda20bf/docs/exchangeFlow.png)

**Comment by szerintedmi** [comment]
Lock flow first pass:
![Lock flow first pass](https://github.com/Augmint/augmint-contracts/raw/3b6b0f6dad22db03b05deab0e1095edf86d4a16b/docs/lockFlow.png)

**Comment by szerintedmi** [comment]
Current sequence diagram versions:
* [Loan flow](https://github.com/Augmint/augmint-contracts/blob/token_refactor/docs/loanFlow.png)
* [Lock flow](https://github.com/Augmint/augmint-contracts/blob/token_refactor/docs/lockFlow.png)
* [Exchange flow](https://github.com/Augmint/augmint-contracts/blob/token_refactor/docs/exchangeFlow.png)

**Comment by szerintedmi** [comment]
Great one, it's on staging branch. Thank you!
